/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jside */

#ifndef _Included_Jside
#define _Included_Jside
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jside
 * Method:    cFunctionName
 * Signature: ([C)[I
 */
JNIEXPORT jintArray JNICALL Java_Jside_cFunctionName
  (JNIEnv *, jobject, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
